source 'http://rubygems.org'

gem 'puppet', '< 3.5'
gem 'rspec-puppet', '~> 1.0.1'
gem 'rake', '~> 10.2.2'
gem 'puppetlabs_spec_helper', '~> 0.4.1'
gem 'webmock', '~> 1.17.4'
gem 'excon', '~> 0.27.5'
gem 'rspec_junit_formatter', '~> 0.1.6'
gem 'json', '~> 1.8.1'
gem 'mime-types', '< 2.0'
gem 'rest-client', '~> 1.6.7'
